# Define paths
BASE_DIR: '/Users/adityakumar/Developer/Projects/emodb_project'
RAW_DATA_DIR: 'data/raw/emodb'
CSV_DIR: 'data/csv'

# Emotion Mapping path
EMOTION_MAPPING_PATH: 'config/emotion_config.yaml'