# Define paths
BASE_DIR: '/Users/adityakumar/Developer/Projects/emodb_project'
RAW_DATA_DIR: 'data/raw/emodb'
CSV_DIR: 'data/csv'
# TODO: Will be implemented in future
# LOG_DIR: 'output/logs'

# Emotion Mapping path
EMOTION_MAPPING_PATH: 'config/emotion_config.yaml'