# EmoDB Emotion Mapping Configuration

emotion_mapping:
  W: anger      # Ã„rger (Wut)
  L: boredom    # Langeweile
  E: disgust    # Ekel
  A: fear       # Angst
  F: happiness  # Freude
  T: sadness    # Trauer
  N: neutral    # Neutral

emotion_to_id:
  anger: 0
  boredom: 1
  disgust: 2
  fear: 3
  happiness: 4
  sadness: 5
  neutral: 6

num_classes: 7
